### ISSUE TITLE
error on build

### ISSUE THREAD

**Issue by augustomurri** [artemirq/hot-accept-webpack-plugin#44]
webpack 5.53.0
hot-accept-webpack-plugin ^2.0.0-beta.7

Running npm run build i get this error

`[webpack-cli] /var/www/website/themes/tsunami/_dev/node_modules/hot-accept-webpack-plugin/build/HotAcceptPlugin.js:9            const moduleRequest = module.userRequest?.replace(/\\/g, '/');

^  SyntaxError: Unexpected token '.'`

**Comment by artembatura** [comment]
Should be fixed in last version - `4.0.0-beta.2`
